// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Rng$Gridironglory = require("./Rng.bs.js");

for(var _for = 1; _for <= 12; ++_for){
  console.log(Rng$Gridironglory.rollDice(/* () */0));
}

/*  Not a pure module */
