// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Random = require("bs-platform/lib/js/random.js");

Random.self_init(/* () */0);

function rollDie(param) {
  return Random.$$int(6) + 1 | 0;
}

function rollDice(param) {
  return (Random.$$int(6) + 1 | 0) + (Random.$$int(6) + 1 | 0) | 0;
}

exports.rollDie = rollDie;
exports.rollDice = rollDice;
/*  Not a pure module */
